<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>This includes logging in, and creating a new patient</description>
   <name>Create a new patient</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-20T16:43:06</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2b7e6193-ddb6-4fff-b4ed-b1efc11103b1</testSuiteGuid>
   <testCaseLink>
      <guid>34102e96-7faf-47da-9518-1895f5cad6b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ePROMS/1. Log in/1.2. Log in - Staff</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c37e1279-1722-4a85-b0f7-2af27f6d4a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0a9b366-99b8-459b-8c4c-84fe38b0c6cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41d73b61-8920-41bf-9fcb-3b484a083562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ePROMS/2. Create new patient record/2.2a. Create a new patient - with email address</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20f1d919-1fb3-4021-93d0-0f8ecc8501d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f004c05-bb4e-453f-ad7c-571b46d4bece</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56aa60b5-8243-4814-a278-e27abe79ba8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2c214e8-d22e-4026-b8f1-1e83a535501a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dff2ea6-c81d-421f-af86-db924213a994</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5607806-e6c9-4fad-ad24-046edb00c811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a53b77-75e5-4db1-bd8c-c91e1ff1a0eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f931c81e-6f96-49c6-8afd-5359a2e56f37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d9e229d-5bab-47ca-9475-e14a869f1019</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6af4c37d-9931-4fbd-81af-269396fd93f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c62edd0-83ff-4098-aae9-b5877c46d217</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>567db1cf-d69e-4ea3-8d49-ce5bd44decb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ePROMS/2. Create new patient record/2.2b. Send patient Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84359241-d027-462d-9bd4-df0b1b63213b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3870521-ac37-4df2-be1a-bbae0bfc8e3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ePROMS/2. Create new patient record/2.2c. Log in to gmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc578510-758b-4bb2-8019-154d7fa55438</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7173787c-2541-4935-b24d-81b77e7dec54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac2258d1-f76f-46d2-ad21-f0b02f914a65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ePROMS/2. Create new patient record/2.2d. Check first email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6146243-463f-464c-9f76-33d04a2a3473</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e4e9cbb-6f8f-4aec-ae52-8e949151d497</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ePROMS/2. Create new patient record/2.2e. Verify email and create account</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
